spring.application.name=food-service
server.address=0.0.0.0
server.port = 8081

spring.datasource.url=jdbc:postgresql://localhost:5432/DeliveryDotCom?createTableIfNotExists=true
spring.datasource.username=postgres
spring.datasource.password=Puneeth@018
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka